### ISSUE TITLE
GCM Client does not receive notifications when app is not running

### ISSUE THREAD

**Issue by bpress** [Redth/GCM.Client#2]
Hi.
It seems I'm stuck with this problem: when the app is active or in the background (i.e. it is listed among the active processes), the library works fine.

Where the app is killed by swiping it away from the recent apps, or when the phone is rebooted, I cannot get any receiver to get the intent and start the related service.

I've tried any combination of permissions and Intent Filters on my BroadcastReceiver class but nothing happens.

Your Android Client Sample (in PushSharp) behaves in the same way.

Can you help?
Thanks!

**Comment by mole440** [comment]
+1 - Notifications are not received when the app is not running, regardless of whether the ActionBootCompleted intentfilter is set or not

**Comment by Totemika** [comment]
Deploy in Release mode instead of Debug, that worked for me.

**Comment by swijnands** [comment]
I second Totemika's recommendation.

Running the app in the Visual Studio debugger, stopping it and then sending a notification does not work: the application does not receive the intent.

The **solution** (for me) was to **start** the (debug build) **application manually** via the application menu on the device, **and then close it** (Running Tasks lists -> Swipe right).

That being said, do not forget to add the:

```
[IntentFilter(new[] { global::Android.Content.Intent.ActionBootCompleted })]
```
to the broadcast receiver class.

And add 

```
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
```
To the *AndroidManifest.xml*

**Comment by ManoLangra123** [comment]
Following can help to solve this issue. I resolved using same code.
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<application>
 <intent-filter>

                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <category android:name="android.intent.category.HOME"/>
 </intent-filter>
add this class file : 
public class BootCompletedIntentReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {

            Intent notification_intent = new Intent(context, NotificationFragment.class);
            context.startService(notification_intent);
        }
    }

**Comment by Redth** [comment]
I've added the missing permission to the sample
