### ISSUE TITLE
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED in Droid project of XF

### ISSUE THREAD

**Issue by rohitvipin** [Redth/GCM.Client#5]
I wanted to give this a try and I added it to my Droid project of Shared Application Xamarin Forms project. 

I get this error on debugging after adding the component, When I remove it, the error goes away. 
Anything to be taken care of in using it in XF? 

Deployment failed because of an internal error: Unexpected install output: 	pkg: /data/local/tmp/ClassroomResponderStudentApp.Droid-Signed.apk
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

Xamarin.AndroidTools.AndroidDeploymentException: InternalError ---> Mono.AndroidTools.InstallFailedException: Unexpected install output: 	pkg: /data/local/tmp/ClassroomResponderStudentApp.Droid-Signed.apk
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass2c.<InstallPackage>b__2b(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.AndroidTools.AndroidDeploySession.RunLogged(CancellationToken token)
   at Xamarin.AndroidTools.AndroidDeploySession.Start(CancellationToken token)

**Comment by rohitvipin** [comment]
@Redth - Any Idea? is there something that I need to change in the manifest?

**Comment by Redth** [comment]
Yep you need to make sure your package name starts with a lowercase letter.

**Comment by rohitvipin** [comment]
So once I install the component for Xamarin Android, What do I need to change?

**Comment by Redth** [comment]
You need to change your android application's package name in the `AndroidManifest.xml`

**Comment by rohitvipin** [comment]
Great. Thank you. I got the error to go away
